### ISSUE TITLE
Add test coverage metrics to jest config and add github action(s) to ensure them

### ISSUE THREAD

**Issue by tracker1** [JamieLivingstone/node-clean-architecture#1]
This is beyond the code strictly speaking, but would be a decent idea to add a test coverage requirement (matching the current coverage level) to the jest configuration.

Then adding a github action to require the coverage is met in pull requests.

Optionally, adding another action, that will update the coverage levels to the current level when merged.

**Comment by JamieLivingstone** [comment]
Hey,

I think that it would be a great addition! Codecov offers this exact functionality and is free for open-source projects.

I will get a PR open over the next day or so with the integration as I am going to add some GitHub actions to:

- Run linting
- Tests (this can include code coverage as part of this step)
- Add badges to the README

Once that's done, I'll add a contribution guideline and hopefully get some contributors.

Thanks for the suggestion!

**Comment by JamieLivingstone** [comment]
Actioned in this [PR](https://github.com/JamieLivingstone/node-clean-architecture/pull/8).

Thank you for the suggestion!
